from django.urls import path
from control import views

urlpatterns = [
    path(
        'login/',
        views.LogInForm.as_view(),
        name="login"
    ),
    path(
        'logout/',
        views.logout_view,
        name="logout"
    ),
    path(
        'user_registration/',
        views.UserRegistrationView.as_view(),
        name="user_registration"
    ),
    path(
        '',
        views.HomePageView.as_view(),
        name="home_page"
    ),
    path(
        'home_page/',
        views.HomePageView.as_view(),
        name="home_page"
    ),
    path(
        'regions/',
        views.RegionsView.as_view(),
        name="regions"
    ),
    path(
        'add_region/',
        views.AddRegionView.as_view(),
        name="add_region"
    ),
    path(
        'edit_region/<int:pk>/',
        views.EditRegionView.as_view(),
        name="edit_region"
    ),
    path(
        'delete_region/<int:region_id>/',
        views.DeleteRegionView.as_view(),
        name="delete_region"
    ),
    path(
        'tags/',
        views.TagView.as_view(),
        name="tags"
    ),
    path(
        'add_tag/',
        views.AddTagView.as_view(),
        name="add_tag"
    ),
    path(
        'edit_tag/<int:pk>/',
        views.EditTagView.as_view(),
        name="edit_tag"
    ),
    path(
        'add_post/<int:pk>/',
        views.AddPostView.as_view(),
        name="add_post"
    ),
    path(
        'add_post_comment/<int:pk>/<int:post_id>/',
        views.AddPostCommentView.as_view(),
        name="add_post_comment"
    ),
]
