# Generated by Django 2.2.6 on 2022-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'STUDENT'), (2, 'DEVELOPER')]),
        ),
    ]
