# Generated by Django 2.2.6 on 2022-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20220322_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'STUDENT'), (2, 'DEVELOPER')], null=True),
        ),
    ]
